name: Build and Release Go Proxy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: windows
            arch: amd64
          - os: darwin
            arch: amd64  # macOS Intel
          - os: darwin
            arch: arm64  # macOS M1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.0'

    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o proxy-${{ matrix.os }}-${{ matrix.arch }}${{ eq(matrix.os, 'windows') && '.exe' || '' }}
      working-directory: ${{ github.workspace }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: proxy-${{ matrix.os }}-${{ matrix.arch }}
        path: proxy-${{ matrix.os }}-${{ matrix.arch }}${{ if eq(matrix.os, 'windows') && '.exe' || '' }}
